jumps: 900
start_date: "2023-06-01 00:00:00"
end_date: "2026-02-05 00:00:00"
root: "./data"
date_format: "%Y-%m-%d %H:%M:%S"
data_path: "./data/btc_15m.csv"
train_interval: ["2023-06-01 00:00:00", "2025-06-01 00:00:00"]
val_interval: ["2025-06-01 00:00:00", "2025-10-01 00:00:00"]
test_interval: ["2025-10-01 00:00:00", "2026-02-05 00:00:00"]
additional_features: []
