data_config: 'btc_30m'
model: 'CMamba_cls_30m'

name: 'CMamba_cls_30m'
max_epochs: 300
batch_size: 256
use_volume: True
additional_features: []

monitor_metric: 'val/accuracy'
monitor_mode: 'max'

hyperparams:
    optimizer: 'adam'
    lr: 0.001
    lr_step_size: 60
    lr_gamma: 0.5
    weight_decay: 0.001
