data_config: 'btc_1h'
model: 'CMamba_cls_1h'

name: 'CMamba_cls_1h'
max_epochs: 500
use_volume: True
additional_features: []

monitor_metric: 'val/accuracy'
monitor_mode: 'max'

hyperparams:
    optimizer: 'adam'
    lr: 0.001
    lr_step_size: 80
    lr_gamma: 0.5
    weight_decay: 0.001
