data_config: 'btc_15m'
model: 'CMamba_cls_15m'

name: 'CMamba_cls_15m'
max_epochs: 500
use_volume: True
additional_features: []

# Classification checkpoint monitoring
monitor_metric: 'val/accuracy'
monitor_mode: 'max'

hyperparams:
    optimizer: 'adam'
    lr: 0.001
    lr_step_size: 80
    lr_gamma: 0.5
    weight_decay: 0.001
